version: '3.8' # Versión de la sintaxis de Docker Compose

services:
  #Servicio de la base  de datos PostgreSQL
  db:
    image: postgres:13-alpine #imagen de postgreSQL
    container_name: productos_db_container #nombre del contenedor
    restart: always
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sasa
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devuser -d productos_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  #Microservicio de Productos
  productos-service:
    build: ./productos-service
    container_name: productos_service_container
    restart: on-failure #reinicia si falla
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productos_db # Usa el nombre del servicio 'db' para la URL de la DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sasa
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      db:
        condition: service_healthy # Espera hasta que el healthcheck de 'db' pase

volumes:
    db_data: # Define el volumen nombrado para persistir los datos de la base de datos